url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: AGR DIGITALBUSSINES
email: agrdigitalbussines@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Andrés Rodríguez
  pic: 2
  position: Founder and CEO
  social:
    - title: twitter
      url: https://twitter.com/AGRDIGITALBUSNS
    - title: blogger
      url: https://bit.ly/androd_vblog
    - title: linkedin
      url: https://www.linkedin.com/in/andresgrodriguez/

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AGRDIGITALBUSNS
  - title: Blogger
    url: https://bit.ly/androd_vblog
  - title: facebook
    url: https://www.facebook.com/profile.php?id=800804465
  - title: linkedin 
    url: https://www.linkedin.com/in/andresgrodriguez/
  - title: github
    url: https://github.com/AGRDIGITALBUSSINES

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty